Configuration:
  status: INFO
  Properties:
    Property:
    - name: pattern
      value: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p %c{1}:%L -%m%n"
  Appenders:
    Console:
      name: CONSOLE
      target: SYSTEM_OUT
      ThresholdFilter:
        level: INFO
        onMatch: ACCEPT
        onMismatch: DENY
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p %c{1}:%L -%m%n"
  Loggers:
    Root:
      level: INFO
      AppenderRef:
      - ref: CONSOLE
    Logger:
    - name: cn.codelion
      additivity: false
      level: DEBUG
      AppenderRef:
      - ref: CONSOLE
